version: '2.2'

services:
  minecraft:
    build: .
    volumes:
      - minecraft-data:/data
    ports:
      - "25566:25566"
      - "25576:25576"
    restart: always

volumes:
  minecraft-data:
    driver: local
